echo ""
echo -n "Today is "; date "+%m-%d-%Y %H:%M:5S"
echo ""
cal 
echo ""
echo ""
#echo -n "Uptime: "; 
#uptime
#echo ""

export HISTSIZE=10000 
export HISTFILESIZE=1000000
export HISTCONTROL=ignoreboth           # ignoredups:ignorespace
export HISTIGNORE="history:pwd:exit:df:ls:ls -la:ll"

alias ll='ls -lahG'
alias home='cd ~'
alias up='cd ..'
alias pdw='pwd'

PS1="\e[0:32m\$ \! \t ==>  \e[m "

#Supress the notification that there is a new default shell
export BASH_SILENCE_DEPRECATION_WARNING=1

#Set Nano as the default editor
export EDITOR=Nano
